version: '3'

services:
         db:
                image: postgres
                restart: always
                container_name: database
                environment:
                        POSTGRES_DB: user_db
                        POSTGRES_USER: priyanka
                        POSTGRES_PASSWORD: admin@123
                ports:
                        -   "5432:5432"
                networks: 
                        -   notejam
                volumes:
                        -   db_data:/var/lib/postgresql/data

         web:
                 build: .
                 image: notejam:django
                 restart: unless-stopped
                 container_name: web
                 command: bash -c "python manage.py syncdb && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
                 ports: 
                        -   "8000:8000"
                 networks:
                        -   notejam
                 depends_on:
                        -   db

networks:
        notejam:
volumes:
        db_data:
       
