apiVersion: v1
kind: Service
metadata:
        name: tekton-notejam-service
        namespace: priyanka
        labels:
                tier: frontend
spec:
        selector:
                tier: frontend
        ports:
        - protocol: "TCP"
          port: 80
          targetPort: 8000
        type: NodePort

    
